### ISSUE TITLE
Umbraco 7.6/7.7 install issue - no localization

### ISSUE THREAD

**Issue by JohnBergman** [thecogworks/examineinspector#1]
The package installs, but none of the strings are localized on either 7.6 or 7.7.

In my case, I needed to copy en-GB to en-US in order for the fields to appear.

**Comment by mzajkowski** [comment]
Thanks for reporting this @JohnBergman. We will take a look on this and get back to you.

**Comment by JohnBergman** [comment]
No Worries, after placing the additional file, it is working fine for me.  I am thinking you may want to add some additional material indicating that the files are there for localization, and perhaps add a fallback mechanism to a default one if there isn't one matching the culture.

**Comment by mzajkowski** [comment]
FYI here: I'm starting working on it. Will update the thread when it will be done.

**Comment by mzajkowski** [comment]
Fixed in #2
